app/admin/models.py
from app import db

class sysUser(db.Model):
    __tablename__ = "admin"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique = True)
    password = db.Column(db.String(256))

    def __init__(self, username='', password=''):
        self.username = username
        self.password = password

    @classmethod
    def search_by_name(cls, name):
        return db.session.query(cls).filter(cls.username == name).first()

    @classmethod
    def get_user_by_id(cls, user_id):
        return db.session.query(cls).get(user_id)

app/admin/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import Required

class adminForm(Form):
    username = TextField('username', validators = [Required()])
    password = PasswordField('password', validators = [Required()])

app/admin/views.py
#coding=utf-8

import traceback

from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import session
from flask import url_for


from jinja2 import TemplateNotFound

from models import sysUser
from forms import adminForm
from login import login_required, after_login

from app import bcrypt
from app import db, app

from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_admin import BaseView, expose, AdminIndexView

from app.education.models import Course, User_course
from app.user.models import regUser

from app.education.updata_user_courses import updata
from app.education.update_allCourse_single import updata_allCourses
from app.education.courses_lis import urp_courses

from gevent.monkey import patch_all
patch_all()

from gevent.pool import Pool
from time import time

manage = Blueprint('manage', __name__, template_folder = 'templates')

@manage.route('/admin_login', methods = ['POST','GET'])
@after_login
def manage_login():
    try:
        admin_form = adminForm()
        if admin_form.validate_on_submit():
            exist_user = sysUser.search_by_name(admin_form.username.data)

            if exist_user and bcrypt.check_password_hash(exist_user.password,
                                                          admin_form.password.data):
                session['user_id'] = exist_user.id

                return redirect(url_for('admin.index'))

            flash("Please check the username and password, and login again!")
        return render_template('admin.html',
                                form = admin_form
                                )
    except:
        traceback.print_exc()

@manage.route('/updata_courses')
@login_required
def update_courses():
    t1 = time()
    urp = urp_courses('2012081507','520134')
    if urp.login():
        urp.course_info()
    else:
        return '提供的用户名或密码错误！'
    t2 = time()
    return '用户课程更新成功\n用时:%fs'%(t2-t1)

@manage.route('/update_courses01')
@login_required
def update_courses_backup():
    courses = Course.query.all()    #update the  user's course info
    for data in courses:
        db.session.delete(data)
    t1 = time()
    allUser = regUser.query.all()
    pool = Pool(12)
    pool.map(updata_allCourses, [[user.username,user.password_urp]
                         for user in allUser]
                     )
    t2 = time()
    return '课程库更新成功，注意重复课程（请进数据库进行冗余操作）\n用时:%fs'%(t2-t1)


@manage.route('/update_user')
@login_required
def update_user():
    userCourses = User_course.query.all()    #update the  user's course info
    for data in userCourses:
        db.session.delete(data)
    t1 = time()
    allUser = regUser.query.all()
    pool = Pool(12)
    pool.map(updata, [[user.username,user.password_urp]
                         for user in allUser]
                     )
    t2 = time()
    return '用户课程更新成功\n用时:%fs'%(t2-t1)

class courseView(ModelView):
    page_size = 20  # the number of entries to display on the list view
    column_searchable_list = ['course_number' ,'course_name']

    def is_accessible(self):
        if 'user_id' in session.keys():
            return True

    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('manage.manage_login'))

class userView(ModelView):
    can_create = False
    page_size = 20  # the number of entries to display on the list view
    column_searchable_list = ['username']

    def is_accessible(self):
        if 'user_id' in session.keys():
            return True

    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('manage.manage_login'))

class userCourseView(ModelView):
    page_size = 20  # the number of entries to display on the list view
    column_searchable_list = ['course_number' ,'username']

    def is_accessible(self):
        if 'user_id' in session.keys():
            return True

    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('manage.manage_login'))

class adminCourseView(ModelView):
    page_size = 20  # the number of entries to display on the list view

    def is_accessible(self):
        if 'user_id' in session.keys():
            return True

    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('manage.manage_login'))

class MyAdminIndexView(AdminIndexView):

    @expose('/')
    def index(self):
        if 'user_id' not in session.keys():
            return redirect(url_for('manage.manage_login'))
        return self.render('admin_index.html')

    @expose('/logout/')
    def logout_view(self):
        """
        logout method, remove the user_id out of session.
        """
        session.pop('user_id', None)
        return redirect(url_for('user.index'))

admin = Admin(
                app, name = 'Wechat_Admin',
                index_view = MyAdminIndexView()
                )

admin.add_view(courseView(Course, db.session, name = u'课程库'))
admin.add_view(userCourseView(User_course, db.session, name = u'用户课程'))
admin.add_view(userView(regUser, db.session, name = u'学生信息'))
admin.add_view(adminCourseView(sysUser, db.session, name = u'管理员'))

app/admin/templates/admin.html
<!DOCTYPE html>
<html>
<head>
  <link href='http://apps.bdimg.com/libs/bootstrap/3.0.3/css/bootstrap.min.css' rel='stylesheet' >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>

    body { background-repeat:repeat}
    .container{width:350px;background:#fff;border-radius:5px;margin-top:15%;padding:15px 10px;}
    .form-title{text-align:center;color:#666;}

  </style>




</head>
  <body>


    <div class='container' >
    <form class="form-horizontal" role="form" action='' method='post'>
     {{form.hidden_tag()}}
    <legend class='form-title'>小偲后台管理</legend>

    <div class="form-group">
     <div class="col-sm-10 col-sm-offset-1">
       {{ form.username(class = 'form-control', placeholder='用户名') }}
   </div>
    </div>

    <div class="form-group">
     <div class="col-sm-10 col-sm-offset-1">
      {{ form.password(class = 'form-control', placeholder='密码') }}

    </div>
    </div>


    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-1" style='text-align:right'>
      <button type="submit" class="btn btn-primary btn-block ">提交</button>
    </div>
    </div>
    {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class="alert alert-danger">
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
    </form>
    </div>

  </body>
</html>

app/admin/templates/admin_index.html
{% extends 'admin/base.html' %}


{% block head %}
<h2 align="center" id="brand"> 微信后台管理中心</h2>
{% endblock %}

{% block access_control %}
<div class="btn-group pull-right">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-user"></i><span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('admin.logout_view') }}">注销</a></li>
    </ul>
</div>
{% endblock %}


{% block body %}
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span4">
			<div class="header">
				<h3 class="text-muted">
				</h3>
			</div>
			<div class="jumbotron well">
				<h1 align = "center">
					课程库更新
				</h1>
				<p class="lead">
                    开学点击此按钮，当课程数量为2k～3k时为正常值，
                    更新时注意课程库课程是否齐全！<br>
				</p>
				<p>
				<button class="btn btn-large btn-success" data-loading-text="Loading..." onclick ="update_courses()">更新</button>
				</p>
			</div>
			<div class="row marketing">
			</div>
		</div>
		<div class="span4">
			<div class="header">
				<h3 class="text-muted">
				</h3>
			</div>
			<div class="jumbotron well">
				<h1 align = "center">
					用户课程更新
				</h1>
				<p class="lead">
                    更新所有用户课程，即清空用户所有课表用爬虫重新
                    抓取（临近期末时全校课程库为空！此时勿点！！）
				</p>
				<p>
				<button class="btn btn-large btn-success" data-loading-text="Loading..." onclick="update_user()">更新</button>
				</p>
			</div>
			<div class="row marketing">
			</div>
		</div>
		<div class="span4">
			<div class="header">
				<h3 class="text-muted">
				</h3>
			</div>
			<div class="jumbotron well">
				<h1 align = "center">
					课程库更新（备）
				</h1>
				<p class="lead">
                    单独获取学生课表(正常情况不建议使用），此方法会产生许多重复课程信息，
                    需要进入数据库批量删除。方法参照操作文档。
				</p>
				<p>
				<button class="btn btn-large btn-danger" data-loading-text="Loading..." onclick="update_courses_backup()">更新（备用）</button>
				</p>
			</div>
			<div class="row marketing">
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
function update_courses(){

$.get("{{url_for('manage.update_courses')}}",function(date){
		alert(date);
	});
}

function update_user(){
$.get("{{url_for('manage.update_user')}}",function(date){
		alert(date);
	});
}

function update_courses_backup(){
$.get("{{url_for('manage.update_courses_backup')}}",function(date){
		alert(date);
	});
}


</script>

<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>

<script>
   $(function() {
      $("button.btn").click(function(){
         $(this).button('loading').delay(1000).queue(function() {
           // $(this).button('reset');
         });
      });
   });
	</script>
{% endblock %}